DROP TABLE newUser;
CREATE TABLE newUser(
 UserId INT IDENTITY,
    Name NVARCHAR(100),
    Email NVARCHAR(100),
    Password CHAR(1000),
    CONSTRAINT PK_User PRIMARY KEY  (UserId)
)
SELECT * FROM newUser